### PR TITLE
(doc) Fix typos in the user guides

### PR DESCRIPTION
**Pull request by thc202**
Fix typos in the user guides, current version and 1.10.

### CODE REVIEW

**Comment by thc202** [comment]
@oheger ping. I didn't see any notification about the PR in the dev mailing list, not enabled for configuration?

**Comment by oheger** [comment]
Sorry, I missed that one. Commons Configuration is not yet integrated with GitHub, so the better option currently is to create a [Jira ticket](http://commons.apache.org/proper/commons-configuration/issue-tracking.html).
Thank you for your patch. I will have a look in a few days.

**Comment by thc202** [comment]
OK, thank you!

**Comment by thc202** [comment]
Closing, applied upstream http://svn.apache.org/r1837978. Thanks!

**Comment by oheger** [comment]
The pull request has been applied to Common Configuration's SVN repository. Please verify and close this PR.

Many thanks again for your contribution!

**Pull request closed without merging**
