### PR TITLE
Checkstyle

### PR DESCRIPTION
**Pull request by mureinik**
This PR fixes existing checkstyle violations in the project and enables checkstyle validation during build time to prevent such issues from reoccurring.

This issue was raised by Gary Gregory on the commons dev list:
http://www.mail-archive.com/dev@commons.apache.org/msg58573.html

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Fixes have been applied in https://github.com/apache/commons-configuration/commit/3644942d2fa6445b6a24b2123fb812d50611915d

Thanks! :+1:

**Comment by mureinik** [comment]
@PascalSchumacher the main point of this PR is failing the build on checkstyle validation (the last patch in the series that changes pom.xml).
This was not merged by 3644942. Is this intentional, or an oversight?

**Comment by PascalSchumacher** [comment]
I think this was intentional, see: https://mail-archives.apache.org/mod_mbox/commons-dev/201706.mbox/%3C3107e1f0-4686-4fc0-74fc-21c86d870b51%40oliver-heger.de%3E

As I remember the discussion at least one main contributor did not like the build to fail for check-style reasons.

**Comment by mureinik** [comment]
> I think this was intentional, see: https://mail-archives.apache.org/mod_mbox/commons-dev/201706.mbox/%3C3107e1f0-4686-4fc0-74fc-21c86d870b51%40oliver-heger.de%3E
> 
> As I remember the discussion at least one main contributor did not like the build to fail for check-style reasons.

Oh, right, thanks!
I saw no discussion *here*, and completely forgot about the discussion there.

**Pull request closed without merging**
