### PR TITLE
CONFIGURATION-808 - DefaultListDelimiterHandler.escapeList working only for List<String>

### PR DESCRIPTION
**Pull request by cigaly**
Test case and fix for https://issues.apache.org/jira/browse/CONFIGURATION-808

### CODE REVIEW

**Comment by garydgregory** [comment]
@cigaly May you please rebase on master?

**Comment by cigaly** [comment]
Done ... hopefully correct. It is now passing under JDK 16 & JDK 17. However, fails under JDK 18 :-)

**Comment by garydgregory** [comment]
@cigaly 
PR is too messy IMO, 46 files changed? Surely this can be boiled down to the essentials. I looks like something went wrong during a merge maybe?

**Comment by cigaly** [comment]
I can create completely new pull request if you like.

Anyway, attached is diff of changes.

[CONFIGURATION-808.txt](https://github.com/apache/commons-configuration/files/7007494/CONFIGURATION-808.txt)

**Comment by garydgregory** [comment]
> I can create completely new pull request if you like.
> 
> Anyway, attached is diff of changes.
> 
> [CONFIGURATION-808.txt](https://github.com/apache/commons-configuration/files/7007494/CONFIGURATION-808.txt)

I want a clean PR such that GirHub runs all our builds. Whatever you've done seems worse since now 47 files are updated.

**Comment by cigaly** [comment]
Closed this PR, and created fresh one

**Pull request closed without merging**
