### PR TITLE
Version bumps

### PR DESCRIPTION
**Pull request by darkma773r**
bumping to commons-parent 53, spring 5.3.19, codeql-action 2

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
I think it needs a `changes.xml` entry too.

**Comment by darkma773r** [comment]
Ah. I didn't realize we were creating changes entries for that. Should I create an entry for this change as well? https://github.com/apache/commons-configuration/pull/140

**Comment by kinow** [comment]
Not small changes like that one, or fixing imports, simplifying a bit shift operation, etc. Unless you feel like there's a risk that that change could cause a regression.

Updates to dependencies normally go to `changes.xml`, including the Commons Parent, e.g. https://github.com/apache/commons-lang/blob/80889fc45cbfb3da0a916e0fc0d51663bb970c2a/src/changes/changes.xml#L283

But if you have multiple updates in a single PR, you can add a single entry with one update per line, e.g. https://github.com/apache/commons-configuration/blob/69260fa1e9c4f87b1abf1c301825a53a722b6007/src/changes/changes.xml#L103-L107

**Comment by kinow** [comment]
For dependabot updates, I add an entry, squash the commits, and push-force and merge :+1:

**Comment by darkma773r** [comment]
How is this?

**Review by kinow — APPROVED** [review]

**Comment by darkma773r** [comment]
Thanks, @kinow!

**Pull request merged**
